image:
  repository: ghcr.io/norskhelsenett/copy-fail-destroyer
  tag: ""  # defaults to appVersion
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

metrics:
  port: 9100
  prometheusScrape: true
  podMonitor:
    enabled: false
    interval: 60s
    scrapeTimeout: 10s
    labels: {}
  prometheusRule:
    enabled: false
    labels: {}
    extraAlertLabels: {}
    #  team: platform
    #  environment: production

namespace:
  create: true
  podSecurityLabels: true

tolerations: []

nodeSelector: {}
